version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.1.0
jobs:
  build:
    # pre-built images: https://circleci.com/docs/2.0/circleci-images/
    docker:
      - image: cimg/node:17.2-browsers
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      - run:
          name: Code Has Arrived
          command: |
            ls -al
            echo '^^^That should look familiar^^^'
      #- run:
      #    name: Build and push Docker image to Heroku
      #    command: |
      #      set -x
      #      sudo curl https://cli-assets.heroku.com/install.sh | sh
      #      HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
      #      HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push -a circle-ci-tutorial web
      #      HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release -a circle-ci-tutorial web
            
