version: 2.1

orbs:
  node: circleci/node@1.1.6
  heroku: circleci/heroku@1.2.6

jobs:
  build_frontend:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: cd frontend; npm install

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run test
          command:  cd frontend; npm test
  build_backend:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: cd backend; npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run test
          command:  cd backend; npm test

workflows:
  heroku_deploy:
    jobs:
      - build_frontend
      - build_backend
      - heroku/deploy-via-git:  
          requires:
            - build_backend
			- build_frontend
          filters:
            branches:
              only: master
